#!/usr/bin/env python3
"""Flatten Assets.xcassets into loose bundle resources for the armv7 build.

`actool` is a closed-source macOS binary, so an asset catalog cannot be
compiled on Linux.  iOS 9 loads loose files through UIImage(named:) perfectly
well -- YTNine ships exactly this layout -- so the catalog is flattened at
BUILD TIME into the staging directory.  Nothing is copied into the repo:
upstream can change any icon and the next build picks it up, with no
duplicated PNGs to drift and no merge conflicts.

Two things the catalog carries that loose files cannot:

  * scale suffixes.  A catalog's `@1x` file becomes the unsuffixed name.
  * rendering intent.  30 of 31 imagesets are `template`, and a loose PNG has
    nowhere to record that, so tinting would silently stop working.  The names
    are emitted into a generated Swift manifest that LegacyAssets consults.

    flatten-assets.py --catalog Opaline/Assets.xcassets --out build/staging
"""

import argparse
import json
import shutil
import sys
from pathlib import Path


def flatten_imagesets(catalog: Path, out: Path):
    """Copy each imageset's files to the bundle root, dropping the @1x suffix."""
    templates, copied = [], 0
    for contents in sorted(catalog.glob("*.imageset/Contents.json")):
        meta = json.loads(contents.read_text())
        name = contents.parent.stem
        intent = meta.get("properties", {}).get("template-rendering-intent")
        if intent == "template":
            templates.append(name)
        for image in meta.get("images", []):
            filename = image.get("filename")
            if not filename:
                continue
            scale = image.get("scale", "1x")
            # UIImage(named:) resolves "foo" -> foo.png / foo@2x.png / foo@3x.png
            suffix = "" if scale == "1x" else f"@{scale}"
            shutil.copy2(contents.parent / filename, out / f"{name}{suffix}.png")
            copied += 1
    return templates, copied


def flatten_appicon(catalog: Path, out: Path):
    """App icons become loose files named by their pixel size, listed in
    CFBundleIconFiles.  Entries an old toolchain cannot express -- the
    Xcode 15 `luminosity: dark` variant -- are skipped."""
    sets = list(catalog.glob("*.appiconset/Contents.json"))
    if not sets:
        return []
    meta = json.loads(sets[0].read_text())
    names = []
    for image in meta.get("images", []):
        filename = image.get("filename")
        if not filename or image.get("appearances"):
            continue                      # dark/tinted variants: iOS 18 only
        if image.get("idiom") == "ios-marketing":
            continue                      # App Store artwork, not a bundle icon
        shutil.copy2(sets[0].parent / filename, out / filename)
        if filename not in names:
            names.append(filename)
    return names


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--catalog", default="Opaline/Assets.xcassets")
    ap.add_argument("--out", required=True)
    ap.add_argument("--manifest", help="path for the generated Swift manifest")
    args = ap.parse_args()

    catalog, out = Path(args.catalog), Path(args.out)
    if not catalog.is_dir():
        print(f"no catalog at {catalog}", file=sys.stderr)
        return 1
    out.mkdir(parents=True, exist_ok=True)

    templates, copied = flatten_imagesets(catalog, out)
    icons = flatten_appicon(catalog, out)

    # AccentColor.colorset is deliberately dropped: named colors in a catalog
    # are iOS 11+, the set is empty, and nothing references UIColor(named:).
    colorsets = [p.stem for p in catalog.glob("*.colorset")]

    if args.manifest:
        listed = "\n".join(f'        "{n}",' for n in sorted(templates))
        Path(args.manifest).write_text(
            "// Generated by scripts/legacy/flatten-assets.py -- do not edit.\n"
            "//\n"
            "// Loose PNGs cannot record a rendering intent, so the names the\n"
            "// asset catalog marked `template` are carried here instead.\n"
            "enum LegacyAssetManifest {\n"
            "    static let templateNames: Set<String> = [\n"
            f"{listed}\n"
            "    ]\n"
            "}\n", encoding="utf-8")

    print(f"  imagesets flattened : {copied} files, {len(templates)} template-rendered")
    print(f"  app icons           : {len(icons)}")
    print(f"  colorsets dropped   : {len(colorsets)} ({', '.join(colorsets) or 'none'})")
    print(f"  CFBundleIconFiles   : {icons}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
